let productItemsData = [
    {
        id: "gfdgdf",
        brand: "Sleepzzz",
        name: "Sleeping bag",
        price: 45,
        desc: "Donec accumsan consectetur faucibus. YOLO, you only live once. Donec eget semper eros. Vestibulum lobortis eros vel elementum suscipit. Nunc tempus lectus elit, et faucibus ligula dignissim nec.",
        img: "img/sleeping-bag.jpg",
    },
    {
        id: "gdfdf",
        brand: "Sleeping tree",
        name: "Hammock",
        price: 45,
        desc: "Phasellus in turpis porta, laoreet sapien vitae, auctor ante.  Your chick, she so thirsty, nec consequat dui imperdiet eget. In quis rhoncus sem, eu eleifend purus. Etiam sodales turpis volutpat.",
        img: "img/hammock.jpg",
    },
    {
        id: "gdfg",
        brand: "Sleeping tree",
        name: "Sleeping bag",
        price: 40,
        desc: "Semper dolor commodo eget. Yltricies blandit. Swaggityswag Donec pretium tincidunt mi.Semper dolor commodo eget. Yltricies blandit. Swaggityswag Donec pretium tincidunt mi.",
        img: "img/sleeping-bag.jpg",
    },
    {
        id: "hammock",
        brand: "Swing Sleep",
        name: "Hammock",
        price: 80,
        desc: "Phasellus in turpis porta, laoreet sapien vitae, auctor ante.  Your chick, she so thirsty, nec consequat dui imperdiet eget. In quis rhoncus sem, eu eleifend purus. Etiam sodales turpis volutpat.",
        img: "img/hammock.jpg",
    },
    {
        id: "tent",
        brand: "Brandname",
        name: "Tent",
        price: 350,
        desc: "Semper dolor commodo eget. Yltricies blandit. Swaggityswag Donec pretium tincidunt mi.Semper dolor commodo eget. Yltricies blandit. Swaggityswag Donec pretium tincidunt mi.",
        img: "img/tent.jpg",
    },
    {
        id: "cooking",
        brand: "Fire it up",
        name: "Cooking",
        price: 10,
        desc: "Donec accumsan consectetur faucibus. YOLO, you only live once. Donec eget semper eros. Vestibulum lobortis eros vel elementum suscipit. Nunc tempus lectus elit, et faucibus ligula dignissim nec.",
        img: "img/cooking.jpg",
    },
];
